version: "3.8"
services:
  dash-app:
    build: .
    ports:
      - "8050:8050"
      - "5679:5679" # Debug port
    environment:
      - SERVER_HOST=0.0.0.0
      - DEBUG_MODE=true
    networks:
      - app-network
    volumes:
      - .:/app
networks:
  app-network:
    driver: bridge
    name: bookscraper-network
