version: "3.8"
services:
  dash-app:
    build: .
    ports:
      - "8050:8050"
    environment:
      - SERVER_HOST=0.0.0.0
    networks:
      - app-network
networks:
  app-network:
    external: true
